version: "3.8"

services:
  mongodb_qfood:
    container_name: mongodb
    image: library/mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: quarkus
      MONGO_INITDB_ROOT_PASSWORD: quarkus
      MONGO_INITDB_DATABASE: admin
